apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-healthcare-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-healthcare-backend
  template:
    metadata:
      labels:
        app: ai-healthcare-backend
    spec:
      containers:
        - name: backend
          image: ai-healthcare-backend:latest
          ports:
            - containerPort: 8000
